### ISSUE TITLE
Some Assorted Suggestions

### ISSUE THREAD

**Issue by TechnoMysterio** [daedalus4096/ThaumicWonders#10]
After having a tinker with some of the things this mod has to offer, I've had some thoughts and suggestions for you to have a quick look at. The stuff in this mod is very good, but I do think that some of these suggestions may help to make it even better:

- Everburn Urn. I do like the idea of a lava counterpart to the Everfull Urn, and I have seen versions of this item in old addons for TC4, but I feel this may be a little too powerful. It does use quite a lot of Vis, but I'm not sure that's enough. The old TC4 addon's Urn used Ignis and Terra CV from nodes to generate lava, which seemed a little more reasonable, and there is also the Hedge Alchemy recipe from base Thaumcraft 6 which can make lava from Terra and Ignis, so maybe the Everburn Urn uses Vis from the chunk as usual but also a small supply of Ignis essentia too?
- Timewinder. Very powerful, especially if it were to be used on a server with other players, so maybe it needs something like a Primordial Pearl in its recipe as well as the already present ingredients? Messing with time is something that shouldn't be too easy, especially in terms of lore, so a Primordial Pearl would make sense for use in crafting such a powerful object. Having it make more Flux might make it a little better too, since it makes it a lot riskier to use, especially when messing with reality.
- Dimensional Ripper. Very cool idea, and much nicer than dumping flux into the aura. However, it's not particularly clear when a pair of the devices are actually the right distance apart, so maybe energy shoots between them when they're connected and ready to take in Vitium? The art for the ripper is a bit lacking as well, maybe tweak it so it looks more like the Void Siphon or the Stabilizer, with a pointed end that magical energy shoots out of. The Void Siphon especially, since that model uses the fancy star-field effect that Flux Rifts and the End Portal also use, which would make sense if used for something that punches holes in the fabric of reality.
- Tweaks to writing. The writing for the mod is generally good, but there are one or two things that might be good to alter. Firstly, the name of the Thaumonomicon tab would be better if it was just one word, probably just 'Wonders'. This would make sure that it matches up with the base Thaumcraft tabs like 'Artifice' or 'Alchemy', or even tabs from other addons, like how Thaumic Periphery just calls its tab 'Periphery'. Some of the more lorey stuff could also do with being altered, like how the Everburn Urn uses portals to get lava even though that can come before discovering Magic Mirrors, or maybe consider adding some extra detail to the bonus Hedge Alchemy recipes explaining how the things are made, like infusing stone with alien essentia makes it End Stone. I dunno, I guess I'm just nitpicking at this point.

Just some small things I noticed, so don't take it too seriously. Either way, keep up the excellent work on this addon!

**Comment by daedalus4096** [comment]
Thank you for the feedback!  It always makes me happy to hear that someone has enjoyed my work.  Regarding your suggestions:

- Having the Everburning Urn consume Ignis essentia is an interesting idea.  The main reason I didn't do that to begin with (besides the question of how to get it in there; piping doesn't make much sense for a jar) is that most other devices don't.  The most pertinent example would be the Infernal Furnace, which I know used to consume Ignis essentia and now just uses vis.  Still, it's worth thinking on.
- For the Timewinder, I didn't want it to be a truly endgame item, so I skipped on the pearl.  Manipulating time is convenient, but it doesn't provide a lot of mechanical benefit, like granting resources would.  That said, you're right that it's perhaps a little too mild to reflect what it's doing lore-wise.  An increase in the flux that it causes wouldn't be uncalled for.
- You're right that the model for the Dimensional Ripper is a little lacking.  Sadly, the artist friend who makes my textures isn't a modeler, and my own skills are quite limited.  I can try to put something more visually appealing together, but that's time that I could be using to make new features, so it's a tradeoff.
- I wanted it to be clear in game what mod these items were coming from, hence the full name in the Thaumonomicon tab.  I'm pretty happy with where the rest of the writing is, though.

Again, thank you for taking the time to write up this feedback post.  I don't get a lot of it, so I value what feedback I do get.  I hope you continue to enjoy the mod.

**Comment by TechnoMysterio** [comment]
I really like to see new Thaumcraft addons, especially ones with unique ideas for newer versions of Thaumcraft, they help to fill in the content that was missing since Azanor left Thaumcraft to be maintained. Anyway, some further thoughts about the addon:

- I did notice that the Everburn Urn does take a long time to make a bucket of lava and it uses a lot of Vis to do so, so that's probably balanced enough, especially considering that a Thaumotorium can make buckets of lava can faster if fed the proper essentia without draining the aura too much, which creates a nice balance of pros/cons between the two.
- The main problem I have with the Timewinder is in a server situation, where a player can just spam it to a certain time to the detriment of other players. In this case I suppose the Timewinder may need a means of limiting its effect, so it could produce quite a bit of Flux, but it could also need to be fed with a power supply of some kind, so you might need to charge it with Vis on a pedestal. This would limit its use for spamming, and encourage its use as more of an occasional help, so once in a blue moon you need to go out hunting or something.
- A better model for the Ripper would be good, probably just a simple json model made in something like Blockbench. You could even nick a model from base Thaumcraft and tweak it a bit, like the stabilizer or the void siphon, applying an altered version of the current texture to fit the model perhaps. However, that's just art, the most annoying thing about the Ripper is positioning it correctly, so the biggest suggestion I'd make for it would be to indicate to the player that a pair of Rippers are set up correctly, with a particle effect or something, mentioning this in the book ("The two devices should begin to emit energy once they are set up correctly, these glowing trails simply confirming that they are connected."). This should help to avoid frustrating players confused by a 10 block gap, because that could mean a 10 block space, 10 blocks including the rippers, or 10 blocks including one ripper.
- It's mainly just me being pedantic, but I think single world names for the tabs looks a little better thematically, and 'Wonders' would still clearly indicate that it's the Thaumic Wonders addon tab. As for the other writing, it's all pretty good, the only odd thing I noticed was that each sentence has a two space gap between them, which makes the formatting look a little funky, like a Word document with dodgy justification.

That's about it for the rest of my thoughts on the older stuff, so I'll have to test the latest update to see what else I can nitpick into oblivion there. Ah, 'tis the life of a Minecraft modded user, complaining about things they have no idea about how difficult they are to actually make.

**Comment by Voxel-Friend** [comment]
For the timewinder, might I suggest a cooldown time, so it cannot be spammed? or give it a Vis cost. Or both.

**Comment by Voxel-Friend** [comment]
Also, I could whip up a few models for you for the ripper, I am decent with blockbench. One last thing. There is a dedicated discord for all thaumcraft addon makers, me included. We would be more than happy to have you! https://discord.gg/ZDbwCJ7

**Comment by TechnoMysterio** [comment]
The cooldown time idea would make a lot of sense actually. And do go ahead and join the addon Discord, it's a good place to discuss these sorts of things.

**Comment by daedalus4096** [comment]
I've updated the Timewinder and Dimensional Ripper according to some of your suggestions.  You should see the changes in the next release.  Closing this issue as complete.  Thanks again for the feedback!
