### ISSUE TITLE
1.3.0 Feedback and Suggestions

### ISSUE THREAD

**Issue by TechnoMysterio** [daedalus4096/ThaumicWonders#16]
Some more thoughts of mine regarding the stuff from version 1.3.0:

- Void Portal art and looks. As with the old Dimensional Ripper (new one looks great!), the block model and texture is lacking for both entrance and exit. I think a good place to start with improving this would be to make it look more along the lines of an Eldritch Stone pedestal, perhaps with some claws or prongs coming out of it as if the device uses them to channel energy into the portal. This energy could also be shown by arcing electrical effects. The output block could also do with a portal effect, probably with a different colour (red instead of blue?) just to make it clear it's a teleporter output. If the teleport isn't linked or is otherwise not working, the portal effect should vanish on both ends. This should help make it clear as to what the portal system is doing, and should also help make it look a little fancier too.
- Void Portal mechanics. One small thing to add would be a redstone toggle for the portal, so it turns off if it gets an RS signal. This would make controlling the device easier, and should also allow players to be able to maintain the portals without accidently teleporting halfway across the world (right-clicking to place blocks around the portal tends to just teleport you off to the middle of nowhere for instance). Otherwise, the teleportation system is generally quite good, but maybe some other drawbacks aside from producing lots of Flux could be good, since dimensional magic should probably be risky. Maybe the portal needs to be stabilized with Stabilizers, as with Flux Rifts? Unstabilized portals could produce much more flux than stablized ones, which could produce only a little. Unstabilized portals could also dump you out more randomly at the other end. Just some thoughts, since player teleportation should be fairly tricky, although the fact that it's pretty much end-game Eldritch is also a good limitation in itself.
- Final Void Portal thoughts. The teleport sound only plays at the entrance, so teleporting long distance is completely silent, so make sure to play the teleport sound at the exit as well. Also... okay I think I've nitpicked enough about the portal, time to nitpick something else instead.
- Hexamite. Good lord this stuff is dangerous. Blowing one up almost always makes a Flux Rift. For this level of destruction, maybe the crafting recipe should be harder. Perhaps an infusion with TNT at the centre and Flux Shards, Alumentum and other explosive ingredients on the outside with appropriate essentia (perditio, vitium, mortuus perhaps)? Either that or make Hexamite slightly less devastating, since the Causality Collapser is already an explosive that is crafted via infusion, so another one might be a little redundant, so nerfing Hexamite a little might be another way to justify its fairly simple crafting recipe.
- Catalyzation Chamber. I like this, there's not much that I think needs altering.

That sums up most of my thoughts on 1.3.0. I've yet to test 1.4.0, but I look forward to trying it out! If you want we can discuss this more on the addon Discord if that're more convenient for you, so just ping me there if you want to do that.

**Comment by daedalus4096** [comment]
Thanks for the additional feedback!  Regarding your points:
- A new model for the Portal Anchor and Generator would be nice.  It's just a question of budgeting time and energy.
- I don't want to have a portal at the anchor exit.  I think it would be confusing to players to see a portal that they can't interact with, even if it was recolored to make it distinct from the entry portal.
- Having the entry portal vanish if the link is somehow broken is something I initially wanted to do, but it's hard from a technical standpoint.  I can take another shot at it, but no promises.
- A redstone toggle for the entry portal makes sense.  I'll see what I can do.
- I'm not very familiar with how the new stabilizers work, but my limited understanding is that they're not compatible with anything other than the infusion matrix.  I don't think they even work with flux rifts anymore.  Unstable portals are an interesting idea, though, and bears further investigation.
- If the teleport sound is only playing at the entrance, that's a bug.  I'll get it fixed.
- Hexamite is supposed to be very dangerous.  Like TNT, it's supposed to illustrate that destroying is always easier than creating.  I might nerf it a little, but I definitely want it to be more powerful than TNT.  Making it harder to craft may be a necessary sacrifice.  But if anything, I want to make a version that's even *more* potent.  /cackle
- Glad you like the Catalyzation Chamber!  I have some expansion plans queued up for it in the next release.

**Comment by TechnoMysterio** [comment]
- Voxel_Friend already offered to help make you a model for the ripper, so if you need it you could always give them a poke on the Discord if you need a hand. Aside from the model the only other thing that might fancy it up would be some particle effects, like electrical arcing or glowing energy.
- That is a good point, instead perhaps have a red portal effect briefly fade in and then out at the exit when a teleport occurs, which should mean that there'll be no confusion as to what the portal is. You can probably nick this effect from the Crimson Portal entity, either Lesser or Greater. This would also kinda make sense in terms of lore, with the whole Crimson Cult teleport reverse-engineering vibe.
- Isn't the portal an entity? If so, could you just kill it/respawn it when the portal is broken/relinked? With some similar opening/closing effects to the Crimson Portals probably.
- I'm fairly certain that the new stabilizers do in fact work with Flux Rifts. I mean, when I plonk one down next to a Rift the device spews Flux out and the Rift starts to stop wiggling/making weird particles. I mean, the Flux Rift entry does say something along the lines of "oh if only I could stabilize these dastardly things somehow". Give it a test if you want, but I'm certain it worked when I needed to stop a Rift from collapsing on a server.
- Unstable portals would be good though, since it's related to the Ripper which makes Rifts, and the portal being naturally unstable as a result would make thematic sense at least. Unstable portals could not only make more flux but also lob you out at the other end or have tendancy to teleport you into a wall or something, it'd make teleportation a risker act.
- Ah, the forces of entropy always outdo those of order it seems. I suppose you could make another research for an even more dangerous bomb if you wanted to, but that itself would likely be best as an infusion recipe. As for the current Hexamite, maybe the Arcane Workbench recipes just needs some additional doodads to make them harder to craft in bulk.
- The Catalyzation Chamber is rather excellent, more conventient ore doubling with some limitations when compared to normal TC ore doubling. I also like how you've neatly justified pinching the Infernal Furnace model by saying that the Chamber is based off of the Furnace's research in the book entry.

I've been keeping an eye on the new stuff that's being added, and it looks very interesting, so I'll definitely give it a whirl when I have a chance.

**Comment by daedalus4096** [comment]
I've incorporated many of your suggestions into the next release.  Unstable void portals won't make it, but it's on my radar for the future.  Closing this issue as resolved.  Thanks again for the good feedback!
