### ISSUE TITLE
Custom ores not being recognized

### ISSUE THREAD

**Issue by LuisEdGm** [daedalus4096/ThaumicWonders#26]
I use ores from Ember:Rekindled and they work just fine for vanilla clusters, i did check the ore dictionary and they are in the correct ore entries (like Copper ore in oreCopper), but they are not recognized by the Catalyzation Chamber.

**Comment by daedalus4096** [comment]
That's very strange.  I already use the ore dictionary to check to see if the ore is allowed, and I know it works with the ores from Thermal Expansion.  I'll look into this when I get a chance.  Thank you for reporting this.

**Comment by LuisEdGm** [comment]
There is something i forgot to mention, i do use several mods that add ores, some of them have repeated ores like Copper and Silver, so i remove all i don't want with scrips and leave the ember's ones, maybe your mod is looking for a specific ore that i removed, i think a workaround could be letting users specify in the config the exact ore they want to use like: 
"Copper Ore: <embers:ore_copper>"

**Comment by daedalus4096** [comment]
So, unfortunately I'm not able to reproduce this issue.  I've tested all three stones using copper ore from Thermal Expansion, Immersive Engineering, and Embers: Rekindled.  All of them work in my test environment.  However, I've added some extra logging in the new 1.5.0 release that should shine a little bit of light on why it's rejecting the ores that it does.  If you can download the new release and post a Pastebin link to a log file from when you're reproducing this issue, that might help me track it down.  Thanks!

**Comment by daedalus4096** [comment]
I was finally able to reproduce this issue, and a potential fix is slated for the next release.
