### ISSUE TITLE
The Sky Goes Black in 1.4.0

### ISSUE THREAD

**Issue by TechnosophyModPack** [daedalus4096/ThaumicWonders#29]
When you look at a block in the world, the sky goes black. Only with this mod installed for me.

**Comment by daedalus4096** [comment]
I'm unable to reproduce this issue, and I have questions.  Is it any block that triggers this behavior, or something specific?  Are you running single-player or on a dedicated server?  What other mods are you running with?  Do you have a log file that you could provide?

**Comment by TechnosophyModPack** [comment]
Hi, unfortunately, there are probably 100 other mods after removing 3/4th of them to find this to be the sky glitch causer, its on server and client, its any block (not fluids or air though), and I know its only when I look at a block because hwyla gui appears to show me block info whenever it occurs. Might be in conjunction with it, and no info appears in log about it client or server. Unfortunately I don't have the log and have removed the mod but I can try to reproduce some time soon. Unfortunately with 450 mods in total in normal use, finding the conflicting mod (if any) would be next to impossible

**Comment by daedalus4096** [comment]
I don't know what to tell you, sorry.  I'm not able to reproduce the issue locally, and without more information I'm not sure where to even begin looking.  My mod doesn't do anything with the skybox.  If you encounter more actionable information, then feel free to reopen this and I'll take another look.  Sorry that I can't help you.

**Comment by TechnosophyModPack** [comment]
okay
