### ISSUE TITLE
Void Fortress Armor Memory Leak?

### ISSUE THREAD

**Issue by Circine** [daedalus4096/ThaumicWonders#53]
If I equip any of the Void Fortress pieces and open my inventory, I can watch java's memory usage in task manager balloon at up to 50MB per second. Minecraft's used/allocated memory doesn't change. The more pieces the faster it rises. This'll go on until I run out of RAM and everything slows to a crawl.
Doesn't seem to happen outside of the inventory screen.

**Comment by shoverno2** [comment]
Some maybe useful information
[latest.log](https://github.com/daedalus4096/ThaumicWonders/files/3719095/latest.log)
[debug.log](https://github.com/daedalus4096/ThaumicWonders/files/3719096/debug.log)

**Comment by bigenergy** [comment]
+1

**Comment by Vapaman** [comment]
Can confirm that it only happens when the armor is rendering.

**Comment by Dearerburrito** [comment]
Alright after some testing with visuals and cosmetic armor I don't think rendering is causing the leak. I think it's more likely to be a bug with warpshell. I think it has to do with the interaction between warp and the special 'Warpshell' enchantment. Maybe a calculation error or a bug with adding extra enchantments to the armor. Either way, can't find a fix.

**Comment by daedalus4096** [comment]
This issue should now be fixed in version 1.8.3.
