### ISSUE TITLE
Disjunction Cloth [Bug]

### ISSUE THREAD

**Issue by xRoBoTx** [daedalus4096/ThaumicWonders#60]
When you disenchant item with Disjunction Cloth NBT tag RepairCost doesnt change backwards.

**Comment by xRoBoTx** [comment]
![image](https://user-images.githubusercontent.com/28825932/63641943-227bf100-c6e1-11e9-8baf-957327d80e5a.png)

**Comment by daedalus4096** [comment]
After doing some investigation, I've determined that this is not a bug.  Enchanting an item doesn't increase its repair cost, only repairing on an anvil does that.  The Disjunction Cloth is just supposed to remove enchantments and their side effects, and repair cost isn't a side effect of enchantment.  Thank you for reporting this, though!
