### ISSUE TITLE
Animated sword.[suggestion, some help]

### ISSUE THREAD

**Issue by shoverno2** [daedalus4096/ThaumicWonders#63]
This addon adds one sword. As thaumonamicon says, it's alive. It's like monster-sword. So, i planing to try do some gif-animation for texture on this week. What do you think?

**Comment by shoverno2** [comment]
for example
![giphy](https://user-images.githubusercontent.com/50020726/66897477-c017e080-efff-11e9-91cb-53e588afc543.gif)

**Comment by shoverno2** [comment]
I wonder to add eyes in animation 🤔

**Comment by daedalus4096** [comment]
Thank you for the thought, but I'm happy with the way that the sword looks as it is.  I think adding animation to it would be a bit much.
