### ISSUE TITLE
Crash on user join

### ISSUE THREAD

**Issue by pyr02k1** [daedalus4096/ThaumicWonders#7]
Morning,
Noted an issue on a test server with a pack I'm working on. User with the Primal Destroyer exits the server with an Internal Server Error, then the user can no longer connect. Another user testing this caught it earlier and then I managed to create it entirely at random just now. I was in game but not moving at all, minimized to edit a config, and noted that I was disconnected via a discord bridge. For testing this, I loaded myself into the world, supplied myself with the Primal Destroyer via JEI Cheat Mode, then checked to see if reconnecting would cause the issue. The playerdata was empty as I'd deleted it before joining, and the only common factor to both was the Primal Destroyer, modpack, both being in luckperms admin group. One was OP, one was not, etc. At that point, a few minor things running around, but otherwise an empty inventory minus some ink sacs. Random in terms of removal times between both.
Solution is to remove the Primal Destroyer from inventory via NBT Explorer or deleting userdata.  

Error from Server Console for the original Internal Server Error. 
https://pastebin.com/w9evnHWD

This is followed by a reconnect attempt showing a network error
https://pastebin.com/18duSHBT

Client side is no help
https://pastebin.com/Vcv7Vkzg

Pack Mods
https://pastebin.com/ycLp5xiD

Sorry, it's 2:30a here and need to head to bed. I can test in any way you'd like and supply the pack and server info on request, as well as SSH to the instance if need be.

**Comment by daedalus4096** [comment]
This issue should be fixed in the next release.
