### ISSUE TITLE
thaumicwonders-1.8.3.jar flagged as trojan.

### ISSUE THREAD

**Issue by ColonistDeme** [daedalus4096/ThaumicWonders#73]
Flagged as "trojan.awind/java. BitDefender, Google, Acronis. Reported as Backdoor malicious component. 

https://www.virustotal.com/gui/file/6b4dedcd8f9b075131f6e8a6a8d5f0a861608c12f3eb733f0b7d8adeb1595816?nocache=1
https://virusscan.jotti.org/en-GB/filescanjob/if9u4o974m
https://metadefender.opswat.com/results/file/bzI0MDUxMjhOSlNNYVRCcmZ5aVJNT0xsako_mdaas/regular/overview

**Comment by xJon** [comment]
Can this be addressed? Really unpleasant to have modpack players worry of getting nalware.

**Comment by daedalus4096** [comment]
I've submitted a false positive report to my antivirus vendor regarding this and am waiting word back. I'll close this issue once they confirm the error. Thank you for the report!

**Comment by xJon** [comment]
@daedalus4096 Do you think that simply rebuilding the mod could somehow result in avoiding the false positive? Might take a while to get all of the false positives go through. We submitted a false positive report to Virus Total a while ago and it's still detected there.

**Comment by ColonistDeme** [comment]
Had no reply from Bitdefender, however, from working with them professionally they'll tend to only reply to actual problems. Their policy is as followed "Bitdefender strives to reduce false-positive reports to a minimum. However, these reports are commonly due to bad programming practices."

BD would push for developers of all applications to resolve themselves rather than adjust their AV Definitions.
VirusTotal does report that this jar uses common ATT&CK techniques although no malware detections were found. 

Even though FP reports have been submitted, I doubt any changes to AV definitions will be made in this circumstance.

**Comment by xJon** [comment]
Just got a report from a user saying that windows defender deleted their Thaumic Wonders jar file so they couldn't connect to a server - I can't verify it but that's really concerning. A solution beyond downgrading to `1.8.2` would be really appreciated.

**Comment by Firebird2099** [comment]
hey,

my bd is detecting it as the follows: Trojan.GenericKD.72487180

i already sent the file to bitdefender labs so they will check it for malware.
Bitdefender told me that they will write me as soon as they hvae checked the file and found out whats wrong with it.

Regards

Firebird2099

**Comment by xJon** [comment]
It seems https://github.com/daedalus4096/ThaumicWonders/commit/33b624549b64ddc582932bfc7a18585c99caeddc is causing the issue.

Tried the following yet malware was still detected:
- Rebuilding the mod as-is
- Correcting the internal version
- Reverting https://github.com/daedalus4096/ThaumicWonders/commit/ee7e904ca11d94ca7b450b20006d25fe8ab40f85

**Comment by Firebird2099** [comment]
Are you very sure that this isnt malware??
I am not intrested in having malware on my pc

**Comment by daedalus4096** [comment]
I've reverted Thaumic Wonders to using Forge 14.23.5.2768 and that seems to have resolved the issue. My antivirus (F-Secure), at least, does not register v1.8.4 as malware. I can't speak to other antivirus providers. The fixed build has been uploaded to Curseforge and is currently awaiting approval. Thank you all for the report.
